version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: fallen
    ports:
      - 3306:3306
  
  starrocks:
    image: starrocks/allin1-ubuntu:3.2.6
    ports:
      - 9030:9030
      - 8080:8080
