source:
  type: mysql
  name: MySQL Source
  hostname: localhost
  port: 3306
  username: root
  password: ""
  tables: fallen.\.*
  server-id: 5400-5500
  server-time-zone: UTC

sink:
  type: starrocks
  name: StarRocks Sink
  jdbc-url: jdbc:mysql://127.0.0.1:9030
  load-url: 127.0.0.1:8080
  username: root
  password: ""
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to StarRocks
  parallelism: 1
  schema.operator.uid: "~SCHEMA_OPERATOR~"

route:
  source-table: fallen.\.*
  sink-table: fallen.terminus